name: Java CI with Maven

on:
  pull_request:
    branches: [ master ]

jobs:
  Prepare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome*.deb

      - uses: nanasess/setup-chromedriver@v1
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Build with Maven
        run: mvn test -Dtest=RunCucumber -Dbrowser=chrome cluecumber-report:reporting

      - name: Test Reporter
        if: always()
        uses: dorny/test-reporter@v1.4.3
        with:
          name: Test Reporter
          path: "**/surefire-reports/TEST-*.xml"
          reporter: java-junit

      - name: Slack Notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: automação-de-testes
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://cdn.icon-icons.com/icons2/1378/PNG/512/dialogerror_92823.png?size=48
          SLACK_MESSAGE: 'Erro na execução de testes :fire:'
          SLACK_TITLE: 'Erro na execução de testes :fire:'
          SLACK_USERNAME: ERRO
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: automação-de-testes
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://pt.seaicons.com/wp-content/uploads/2022/05/sign-check-icon.png?size=48
          SLACK_MESSAGE: 'Sucesso na execução de testes :white_check_mark:'
          SLACK_TITLE: 'Sucesso na execução de testes :white_check_mark:'
          SLACK_USERNAME: SUCESSO
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Archive code coverage results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: "**/formated-report/"